## Hubs
#### Calculate the expected maximum degree kmax for the undirected networks listed in Table 4.1.

In [132]:
from texttable import Texttable
import pandas as pd

In [133]:
# function to convert to subscript 
def get_sub(x): 
    normal = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-=()"
    sub_s = "ₐ₈CDₑբGₕᵢⱼₖₗₘₙₒₚQᵣₛₜᵤᵥwₓᵧZₐ♭꜀ᑯₑբ₉ₕᵢⱼₖₗₘₙₒₚ૧ᵣₛₜᵤᵥwₓᵧ₂₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"
    res = x.maketrans(''.join(normal), ''.join(sub_s)) 
    return x.translate(res) 
  
# function to convert to superscript 
def get_super(x): 
    normal = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-=()"
    super_s = "ᴬᴮᶜᴰᴱᶠᴳᴴᴵᴶᴷᴸᴹᴺᴼᴾQᴿˢᵀᵁⱽᵂˣʸᶻᵃᵇᶜᵈᵉᶠᵍʰᶦʲᵏˡᵐⁿᵒᵖ۹ʳˢᵗᵘᵛʷˣʸᶻ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾"
    res = x.maketrans(''.join(normal), ''.join(super_s)) 
    return x.translate(res)

In [134]:
table_text = Texttable()
table_text.set_cols_width([13,6,8,6,7,8,9,5,5,5])
table_text.add_rows([['Network', 'N', 'L', '<k>', '<k{}{}>'.format(get_sub('in'), get_super('2')), 
                 '<k{}{}>'.format(get_sub('out'), get_super('2')), 
                 '<k{}>'.format(get_super('2')), 
                 'γ{}'.format(get_sub('in')), 
                 'γ{}'.format(get_sub('out')), 
                 'γ'], 
                ['Internet', 192244, 609066, 6.34, '-', '-', 240.1, '-', '-', 3.42], 
                ['WWW', 325729, 1497134, 4.60, 1546.0, 482.4, '-', 2.00, 2.31, '-'], 
                ['Power Grid', 4941, 6594, 2.67, '-', '-', 10.3, '-', '-', 'Exp.'], 
                ['Mobile-Phone Calls', 36595, 91826, 2.51, 12.0, 11.7, '-', 4.69, 5.01, '-'], 
                ['Email', 57194, 103731, 1.81, 9.47, 1163.9, '-', 3.43, 2.03, '-'], 
                ['Science \nCollaboration', 23133, 93437, 8.08, '-', '-', 178.2, '-', '-', 3.35], 
                ['Actor Network', 702388, 29397908, 83.71, '-', '-', 47353.7, '-', '-', 2.12], 
                ['Citation Network', 449673, 4689479, 10.43, 971.5, 198.8, '-', 3.03, 4.00, '-'], 
                ['E. Coli Metabolism', 1039, 5802, 5.58, 535.7, 396.7, '-', 2.43, 2.90, '-'], 
                ['Protein Interactions', 2018, 2930, 2.90, '-', '-', 32.3, '-', '-', 2.89]])
print(table_text.draw())

+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
|    Network    |   N    |    L     |  <k>   | <kᵢₙ²>  | <kₒᵤₜ²>  |   <k²>    |  γᵢₙ  | γₒᵤₜ  |   γ   |
+===============+========+==========+========+=========+==========+===========+=======+=======+=======+
| Internet      | 192244 | 609066   | 6.340  | -       | -        | 240.100   | -     | -     | 3.420 |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| WWW           | 325729 | 1497134  | 4.600  | 1546    | 482.400  | -         | 2     | 2.310 | -     |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Power Grid    | 4941   | 6594     | 2.670  | -       | -        | 10.300    | -     | -     | Exp.  |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Mobile-Phone  | 36595  | 91826    | 2.510  | 12      | 11.700   | -         | 4.690 | 5.010 | -     |
| Calls         |        |          |        |         |          |           |       |       |       |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Email         | 57194  | 103731   | 1.810  | 9.470   | 1163.900 | -         | 3.430 | 2.030 | -     |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Science       | 23133  | 93437    | 8.080  | -       | -        | 178.200   | -     | -     | 3.350 |
| Collaboration |        |          |        |         |          |           |       |       |       |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Actor Network | 702388 | 29397908 | 83.710 | -       | -        | 47353.700 | -     | -     | 2.120 |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Citation      | 449673 | 4689479  | 10.430 | 971.500 | 198.800  | -         | 3.030 | 4     | -     |
| Network       |        |          |        |         |          |           |       |       |       |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| E. Coli       | 1039   | 5802     | 5.580  | 535.700 | 396.700  | -         | 2.430 | 2.900 | -     |
| Metabolism    |        |          |        |         |          |           |       |       |       |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+
| Protein       | 2018   | 2930     | 2.900  | -       | -        | 32.300    | -     | -     | 2.890 |
| Interactions  |        |          |        |         |          |           |       |       |       |
+---------------+--------+----------+--------+---------+----------+-----------+-------+-------+-------+

In [135]:
table_data = {'Network': ['Internet', 'WWW', 'Power Grid', 'Mobile-Phone Calls', 'Email', 'Science Collaboration', 'Actor Network', 'Citation Network', 'E. Coli Metabolism', 'Protein Interactions'], 
     'N': [192244, 325729, 4941, 36595, 57194, 23133, 702388, 449673, 1039, 2018], 
     'L': [609066, 1497134, 6594, 91826, 103731, 93437, 29397908, 4689478, 5802, 2930],
     '<k>': [6.340, 4.600, 2.670, 2.510, 1.810, 8.080, 83.710, 10.430, 5.580, 2.900],
     '<k{}{}>'.format(get_sub('in'), get_super('2')): [None, 1546, None, 12, 9.470, None, None, 971.500, 535.700, None],
     '<k{}{}>'.format(get_sub('out'), get_super('2')): ['-', 482.400, '-', 11.700, 1163.900, '-', '-', 198.800, 396.700, '-'],
     '<k{}>'.format(get_super('2')): [240.100, '-', 10.300, '-', '-', 178.200, 47353.700, '-', '-', 32.300],
     'γ{}'.format(get_sub('in')): ['-', 2, '-', 4.690, 3.430, '-', '-', 3.030, 2.430, '-'], 
     'γ{}'.format(get_sub('out')): ['-', 2.310, '-', 5.010, 2.030, '-', '-', 4, 2.900, '-'], 
     'γ': [3.420, '-', 'Exp.', '-', '-', 3.350, 2.120, '-', '-', 2.890] }
table_df = pd.DataFrame(data=table_data)

# select the undirected networks listed in Table 4.1
table_df.loc[table_df['<k{}{}>'.format(get_sub('in'), get_super('2'))] >= 0, 'Undirected'] = False
table_df.loc[table_df['Undirected'] != False, 'Undirected'] = True
undirected_table_df = table_df.loc[table_df['Undirected'] == True].drop(columns=['<k{}{}>'.format(get_sub('in'), get_super('2')), 
                                                                                 '<k{}{}>'.format(get_sub('out'), get_super('2')), 
                                                                                 'γ{}'.format(get_sub('in')), 
                                                                                 'γ{}'.format(get_sub('out'))])

In [136]:
# add kmin values from table 4.3
kmin_vals = [72, 5, 3.35, 54, 7]
undirected_table_df['k_min'] = kmin_vals

# add value from γ column in table 4.3 to replace Exp.
undirected_table_df.loc[undirected_table_df['γ'] == 'Exp.', 'γ'] = 4.00

In [137]:
num_rows = undirected_table_df.shape[0]

max_degree_list = []

for row in range(num_rows):
    kmax = undirected_table_df['k_min'].iloc[row] * undirected_table_df['N'].iloc[row]**(1/(undirected_table_df['γ'].iloc[row]-1))
    max_degree_list.append(kmax)

undirected_table_df['k_max'] = max_degree_list
undirected_table_df

,Network,N,L,<k>,<k²>,γ,Undirected,k_min,k_max
0,Internet,192244,609066,6.34,240.1,3.42,True,72.00,1.098355e+04
2,Power Grid,4941,6594,2.67,10.3,4.0,True,5.00,8.516117e+01
5,Science Collaboration,23133,93437,8.08,178.2,3.35,True,3.35,2.410820e+02
6,Actor Network,702388,29397908,83.71,47353.7,2.12,True,54.00,8.965033e+06
9,Protein Interactions,2018,2930,2.90,32.3,2.89,True,7.00,3.924041e+02